default: &default
  adapter: postgis
  encoding: unicode
  username: minneapolis
  pool: 5

development:
  <<: *default
  database: minneapolis_development

test:
  <<: *default
  database: minneapolis_test

production:
  <<: *default
  database: minneapolis_production
  username: minneapolis
  password: <%= ENV['MINNEAPOLIS_DATABASE_PASSWORD'] %>
